import { useMemo, useState } from 'react'
import Icon from '../Icon'
import './Teachers.css'

const subjects = ['Mathématiques', 'Physique-Chimie', 'SVT', 'Français', 'Arabe', 'Anglais', 'Philosophie']
const branches = ['Succursale Nord', 'Succursale Sud', 'Succursale Centre']
const initialTeachers = [
  { id: 1, firstName: 'Karim', lastName: 'El Amrani', phone: '0612345678', cin: 'AB123456', address: 'Casablanca', hiredAt: '2024-09-01', subjects: ['Mathématiques'], branches: ['Succursale Nord', 'Succursale Centre'], paymentType: 'fixe', salary: '7000', rates: {}, active: true },
  { id: 2, firstName: 'Salma', lastName: 'Bennani', phone: '0623456789', cin: 'CD234567', address: 'Casablanca', hiredAt: '2024-09-01', subjects: ['Physique-Chimie', 'SVT'], branches: ['Succursale Nord'], paymentType: 'pourcentage', salary: '', rates: { 'Physique-Chimie': '40', SVT: '35' }, active: true },
  { id: 3, firstName: 'Youssef', lastName: 'Tazi', phone: '0634567890', cin: 'EF345678', address: 'Rabat', hiredAt: '2024-10-01', subjects: ['Français', 'Philosophie'], branches: ['Succursale Sud'], paymentType: 'fixe', salary: '6500', rates: {}, active: true },
  { id: 4, firstName: 'Nadia', lastName: 'Idrissi', phone: '0645678901', cin: 'GH456789', address: 'Marrakech', hiredAt: '2024-10-01', subjects: ['Anglais'], branches: ['Succursale Centre', 'Succursale Sud'], paymentType: 'pourcentage', salary: '', rates: { Anglais: '40' }, active: true },
  { id: 5, firstName: 'Omar', lastName: 'Fassi', phone: '0656789012', cin: 'IJ567890', address: 'Casablanca', hiredAt: '2024-11-01', subjects: ['Arabe'], branches: ['Succursale Nord'], paymentType: 'fixe', salary: '6000', rates: {}, active: false },
]

const emptyTeacher = { firstName: '', lastName: '', phone: '', cin: '', address: '', hiredAt: '', subjects: [], branches: [], paymentType: 'fixe', salary: '', rates: {}, active: true }
const Pencil = () => <svg viewBox="0 0 24 24"><path d="m4 16.8-.7 3.9 3.9-.7L18.5 8.7 15.3 5.5 4 16.8Z" /><path d="m13.8 7 3.2 3.2" /></svg>
const Power = () => <svg viewBox="0 0 24 24"><path d="M12 3v8" /><path d="M6.3 5.8a8 8 0 1 0 11.4 0" /></svg>
const Upload = () => <svg viewBox="0 0 24 24"><path d="M12 16V4m0 0-4 4m4-4 4 4M5 14v5h14v-5" /></svg>

function Toggle({ checked, onChange }) { return <label className="teacher-switch"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><i /></label> }

function Header() { return <header className="topbar teachers-topbar"><label className="searchbar"><span className="searchbar__icon"><Icon name="search" /></span><input placeholder="Rechercher un élève, professeur..." /></label><button className="branch-select">Toutes les succursales <span>⌄</span></button><button className="notifications"><Icon name="bell" /><span className="notifications__badge">40</span></button><div className="profile"><div className="profile__avatar">DA</div><div><strong>Directeur Atlas</strong><span>Administrateur</span></div></div></header> }

function TeacherForm({ teacher, onClose, onSave }) {
  const [form, setForm] = useState(teacher ? { ...teacher } : emptyTeacher)
  const set = (field, value) => setForm((current) => ({ ...current, [field]: value }))
  const toggle = (field, value) => set(field, form[field].includes(value) ? form[field].filter((item) => item !== value) : [...form[field], value])
  const setRate = (subject, value) => set('rates', { ...form.rates, [subject]: value })
  const submit = (event) => { event.preventDefault(); onSave({ ...form, id: teacher?.id || crypto.randomUUID() }) }
  const editing = Boolean(teacher)
  return <div className="teacher-form-page"><Header /><main className="teacher-form-content"><div className="teacher-form-heading"><h1>{editing ? 'Modifier le professeur' : 'Nouveau professeur'}</h1><p>Renseignez les informations personnelles et professionnelles.</p></div><form onSubmit={submit}>
    <section className="teacher-card"><h2>Informations personnelles</h2><label className="photo-drop"><Upload /><span>Photo (drag & drop)</span><input type="file" accept="image/*" /></label><div className="teacher-grid"><label>Prénom<input value={form.firstName} onChange={(e) => set('firstName', e.target.value)} required /></label><label>Nom<input value={form.lastName} onChange={(e) => set('lastName', e.target.value)} required /></label><label>CIN<input value={form.cin} onChange={(e) => set('cin', e.target.value)} required /></label><label>Téléphone<input type="tel" value={form.phone} onChange={(e) => set('phone', e.target.value)} required /></label></div><label>Adresse<input value={form.address} onChange={(e) => set('address', e.target.value)} /></label><div className="teacher-date-status"><label>Date d'embauche<input type="date" value={form.hiredAt} onChange={(e) => set('hiredAt', e.target.value)} required /></label><div className="teacher-active"><Toggle checked={form.active} onChange={(value) => set('active', value)} /><span>Actif</span></div></div></section>
    <section className="teacher-card"><h2>Informations professionnelles</h2><fieldset><legend>Matières enseignées</legend><div className="choice-grid">{subjects.map((subject) => <label className={form.subjects.includes(subject) ? 'is-checked' : ''} key={subject}><input type="checkbox" checked={form.subjects.includes(subject)} onChange={() => toggle('subjects', subject)} />{subject}</label>)}</div></fieldset><fieldset><legend>Succursale(s) d'affectation</legend><div className="choice-grid choice-grid--branches">{branches.map((branch) => <label className={form.branches.includes(branch) ? 'is-checked' : ''} key={branch}><input type="checkbox" checked={form.branches.includes(branch)} onChange={() => toggle('branches', branch)} />{branch}</label>)}</div></fieldset><fieldset className="payment-type"><legend>Type de rémunération</legend><div><button type="button" onClick={() => set('paymentType', 'fixe')} className={form.paymentType === 'fixe' ? 'is-selected' : ''}>Fixe</button><button type="button" onClick={() => set('paymentType', 'pourcentage')} className={form.paymentType === 'pourcentage' ? 'is-selected' : ''}>Pourcentage</button></div></fieldset>{form.paymentType === 'fixe' ? <label className="salary-field">Montant mensuel (DH)<input type="number" min="0" value={form.salary} onChange={(e) => set('salary', e.target.value)} required /><small>{form.salary ? `${Number(form.salary).toLocaleString('fr-FR')} DH` : ''}</small></label> : <fieldset className="rates"><legend>Taux par matière (%)</legend>{form.subjects.length ? form.subjects.map((subject) => <label key={subject}><strong>{subject}</strong><span><input type="number" min="0" max="100" value={form.rates[subject] || ''} onChange={(e) => setRate(subject, e.target.value)} required />%</span></label>) : <p>Sélectionnez au moins une matière.</p>}</fieldset>}</section>
    <footer className="teacher-form-footer"><button type="button" onClick={onClose}>Annuler</button><button type="submit">Enregistrer</button></footer>
  </form></main></div>
}

export default function Teachers() {
  const [teachers, setTeachers] = useState(initialTeachers); const [query, setQuery] = useState(''); const [formTeacher, setFormTeacher] = useState(undefined)
  const filtered = useMemo(() => teachers.filter((teacher) => `${teacher.firstName} ${teacher.lastName}`.toLowerCase().includes(query.toLowerCase())), [teachers, query])
  const save = (teacher) => { setTeachers((items) => items.some((item) => item.id === teacher.id) ? items.map((item) => item.id === teacher.id ? teacher : item) : [...items, teacher]); setFormTeacher(undefined) }
  if (formTeacher !== undefined) return <TeacherForm teacher={formTeacher || null} onClose={() => setFormTeacher(undefined)} onSave={save} />
  return <div className="teachers-page"><Header /><main className="teachers-content"><div className="teachers-heading"><div><h1>Professeurs</h1><p>{teachers.length} professeurs enregistrés</p></div><button onClick={() => setFormTeacher(null)} className="teacher-add">♙ <span>Ajouter un professeur</span></button></div><label className="teacher-search"><Icon name="search" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Rechercher par nom..." /></label><div className="teachers-table-wrap"><table className="teachers-table"><thead><tr><th>Professeur</th><th>Matière(s)</th><th>Salaire</th><th>Succursale(s)</th><th>Statut</th><th>Actions</th></tr></thead><tbody>{filtered.map((teacher) => <tr key={teacher.id}><td><div className="teacher-name"><span>{teacher.firstName[0]}{teacher.lastName[0]}</span><div><strong>{teacher.firstName} {teacher.lastName}</strong><small>{teacher.phone}</small></div></div></td><td>{teacher.subjects.map((subject) => <i className="subject-tag" key={subject}>{subject}</i>)}</td><td><span className={`pay-tag ${teacher.paymentType}`}>{teacher.paymentType === 'fixe' ? 'Fixe' : 'Pourcentage'}</span></td><td>{teacher.branches.map((branch) => branch.replace('Succursale ', '')).join(', ')}</td><td><span className={`teacher-status ${teacher.active ? 'active' : ''}`}>{teacher.active ? 'Actif' : 'Inactif'}</span></td><td><div className="teacher-actions"><button onClick={() => setFormTeacher(teacher)} aria-label="Modifier"><Pencil /></button><button className={teacher.active ? '' : 'is-off'} onClick={() => setTeachers((items) => items.map((item) => item.id === teacher.id ? { ...item, active: !item.active } : item))} aria-label="Activer ou désactiver"><Power /></button></div></td></tr>)}</tbody></table></div></main></div>
}
