import { useMemo, useRef, useState } from 'react'
import Header from '../shared/Header'
import Icon from '../Icon'
import { subjects } from '../Students/data/mockStudents'
import { initials, price } from '../Students/utils/studentHelpers'
import { exportToPdf, safeFilename } from '../../utils/exportToPdf'
import './FeesPage.css'
import './FeesEditModal.css'

const months = ['Sept', 'Oct', 'Nov', 'Déc', 'Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Juin', 'Juil', 'Août']
const seed = [
  { id: 1, name: 'Yasmine Alaoui', code: 'REG-2026-1000', level: 'Petite section', chosen: [], monthly: 800, payments: ['paid','paid','paid','paid','due','due','inactive','inactive','inactive','inactive','inactive','inactive'] },
  { id: 2, name: 'Adam Drissi', code: 'REG-2026-1001', level: '2ème année', chosen: [], monthly: 800, payments: ['paid','paid','paid','due','due','inactive','inactive','inactive','inactive','paid','inactive','inactive'] },
  { id: 3, name: 'Lina Ghazi', code: 'REG-2026-1002', level: '9ème (3AC)', chosen: ['Mathématiques','Physique-Chimie','SVT','Français'], monthly: 1300, payments: ['paid','paid','due','due','inactive','inactive','inactive','inactive','paid','paid','inactive','inactive'] },
  { id: 4, name: 'Zakaria Jaidi', code: 'REG-2026-1003', level: 'Tronc commun', chosen: ['Mathématiques','Physique-Chimie','SVT','Français','Anglais'], monthly: 2100, payments: ['paid','due','due','inactive','inactive','inactive','inactive','paid','paid','paid','inactive','inactive'] },
  { id: 5, name: 'Ines Mansouri', code: 'REG-2026-1004', level: 'Formation Pro', chosen: [], monthly: 800, payments: ['due','due','inactive','inactive','inactive','inactive','paid','paid','paid','paid','inactive','inactive'] },
  { id: 6, name: 'Mehdi Peretti', code: 'REG-2026-1005', level: 'Grande section', chosen: [], monthly: 800, payments: ['due','inactive','inactive','inactive','inactive','paid','paid','paid','paid','due','inactive','inactive'] },
]

function Receipt({ student, month, close }) {
  const receiptRef = useRef(null)
  const [isExporting, setIsExporting] = useState(false)
  const lines = student.chosen.length ? student.chosen : ['Forfait tout inclus']
  const amountFor = subject => student.chosen.length ? price(subject) : student.monthly
  const downloadPdf = async () => {
    setIsExporting(true)
    try { await exportToPdf(receiptRef.current, `recu-paiement-${safeFilename(student.name)}-${safeFilename(month)}.pdf`) } finally { setIsExporting(false) }
  }
  return <main className="fee-receipt">
    <div className="fee-receipt-actions"><button onClick={close}>← Retour</button><button className="fee-print" disabled={isExporting} onClick={downloadPdf}>{isExporting ? 'Génération du PDF…' : '▣  Télécharger le PDF'}</button></div>
    <article ref={receiptRef} className="fee-document">
      <header><div className="fee-brand"><img src="/oskar-logo.png" alt="Logo Centre Atlas" /><div><strong>Centre Atlas</strong><span>Cours particuliers — Casablanca</span></div></div><div className="fee-ref"><span>REÇU DE PAIEMENT MENSUEL</span><b>{student.code}</b><small>Date : {new Intl.DateTimeFormat('fr-MA').format(new Date())}</small></div></header>
      <section className="fee-receipt-student"><div>{initials(student.name)}</div><p><strong>{student.name}</strong><span>Niveau : {student.level}</span><span>Mois réglé : {month}</span></p></section>
      <section className="fee-lines"><h2>Détail des matières</h2><div className="fee-line fee-line-head"><span>Matière</span><span>Prix</span></div>{lines.map((line, i) => <div className="fee-line" key={line}><span>{line}</span><span>{student.chosen.length ? (i === lines.length - 1 ? student.monthly - lines.slice(0,-1).reduce((s, x) => s + price(x), 0) : amountFor(line)) : student.monthly} DH</span></div>)}<div className="fee-total"><b>Montant total payé</b><strong>{student.monthly} DH</strong></div></section>
      <div className="fee-confirmation">✓ Paiement reçu en espèces — Le {new Intl.DateTimeFormat('fr-MA').format(new Date())}</div><footer><span>Signature parent/tuteur</span><span>Signature administration</span></footer>
    </article>
  </main>
}

export default function FeesPage() {
  const [students, setStudents] = useState(seed), [query, setQuery] = useState(''), [selected, setSelected] = useState(null), [editing, setEditing] = useState(null), [receipt, setReceipt] = useState(null)
  const shown = useMemo(() => students.filter(s => `${s.name} ${s.code}`.toLowerCase().includes(query.toLowerCase())), [students, query])
  const openPayment = (student, index) => { if (student.payments[index] !== 'inactive') setSelected({ student, index }) }
  const validate = () => { setStudents(list => list.map(s => s.id === selected.student.id ? { ...s, payments: s.payments.map((p, i) => i === selected.index ? 'paid' : p) } : s)); setReceipt({ student: { ...selected.student, payments: selected.student.payments.map((p,i) => i === selected.index ? 'paid' : p) }, month: months[selected.index] }); setSelected(null) }
  const toggleSubject = subject => setEditing(e => ({ ...e, chosen: e.chosen.includes(subject) ? e.chosen.filter(s => s !== subject) : [...e.chosen, subject], subjectDetails: { ...e.subjectDetails, [subject]: e.subjectDetails?.[subject] || { teacher: '', group: '', priceType: 'standard', manualPrice: '' } } }))
  const setSubjectDetails = (subject, changes) => setEditing(e => ({ ...e, subjectDetails: { ...e.subjectDetails, [subject]: { ...e.subjectDetails?.[subject], ...changes } } }))
  const saveEdit = () => { const monthly = editing.chosen.length ? editing.chosen.reduce((sum, subject) => { const details = editing.subjectDetails?.[subject]; return sum + (details?.priceType === 'manual' ? Number(details.manualPrice || 0) : price(subject)) }, 0) : 800; setStudents(list => list.map(s => s.id === editing.id ? { ...editing, monthly } : s)); setEditing(null) }
  if (receipt) return <Receipt {...receipt} close={() => setReceipt(null)} />
  return <div className="fees-page"><Header /><main className="fees-content"><div className="fees-heading"><h1>Comptabilité</h1><p>Gestion financière du centre.</p></div><nav className="accounting-tabs"><button className="active">Frais de scolarité</button><button>Retards & Impayés</button><button>Salaires Profs</button><button>Charges</button><button>Bénéfice net</button></nav>
    <section className="fee-stats"><article><span>Total encaissé</span><strong>160 800 DH</strong></article><article><span>Élèves facturés</span><strong>{students.length}</strong></article><article><span>Dû mensuel total</span><strong>{students.reduce((sum,s) => sum + s.monthly, 0).toLocaleString('fr-FR')} DH</strong></article></section>
    <label className="fees-search"><Icon name="search" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Rechercher un élève..." /></label>
    <div className="fees-table-wrap"><table className="fees-table"><thead><tr><th>Élève</th><th>Niveau</th><th>Matières</th><th>Dû/mois</th>{months.map(m => <th key={m}>{m}</th>)}<th aria-label="Modifier" /></tr></thead><tbody>{shown.map(student => <tr key={student.id}><td><div className="fee-student"><i>{initials(student.name)}</i><span><b>{student.name}</b><small>{student.code}</small></span></div></td><td>{student.level}</td><td>{student.chosen.length}</td><td><b>{student.monthly} DH</b></td>{student.payments.map((state, index) => <td key={index}><button aria-label={`${months[index]} : ${state}`} className={`payment-dot ${state}`} disabled={state === 'inactive'} onClick={() => openPayment(student,index)} /></td>)}<td><button className="fee-edit" onClick={() => setEditing({ ...student, chosen: [...student.chosen], subjectDetails: { ...(student.subjectDetails || {}) } })}><Icon name="pencil" /></button></td></tr>)}</tbody></table></div>
  </main>{selected && <div className="fee-overlay"><section className="payment-modal"><button className="modal-close" onClick={() => setSelected(null)}>×</button><h2>Paiement — {months[selected.index]}</h2><div className="payment-person"><i>{initials(selected.student.name)}</i><span><b>{selected.student.name}</b><small>{selected.student.code}</small></span></div><div className="payment-amount"><span>Montant dû</span><strong>{selected.student.monthly} DH</strong></div>{selected.student.payments[selected.index] === 'paid' ? <><div className="validated">✓ Paiement validé</div><button className="receipt-button" onClick={() => { setReceipt({ student:selected.student, month:months[selected.index] }); setSelected(null) }}>▣ &nbsp; Imprimer le reçu</button></> : <button className="validate-button" onClick={validate}>Valider le paiement</button>}</section></div>}
  {editing && <div className="fee-overlay"><section className="edit-modal"><button className="modal-close" onClick={() => setEditing(null)}>×</button><h2>Modifier les matières & groupes</h2><p>{editing.name} — sélectionnez les matières auxquelles l'élève est inscrit.</p><div className="edit-subjects">{subjects.map(subject => { const selected = editing.chosen.includes(subject); const details = editing.subjectDetails?.[subject] || { teacher: '', group: '', priceType: 'standard', manualPrice: '' }; return <article key={subject} className={selected ? 'selected' : ''}><label className="edit-subject-toggle"><input type="checkbox" checked={selected} onChange={() => toggleSubject(subject)} /><span><b>{subject}</b><small>{price(subject)} DH/mois</small></span></label>{selected && <div className="edit-subject-details"><label>Professeur<select value={details.teacher} onChange={e => setSubjectDetails(subject, { teacher: e.target.value })}><option value="">Choisir un professeur</option><option>Karim El Amrani</option><option>Salma Bennani</option></select></label><label>Groupe<select value={details.group} onChange={e => setSubjectDetails(subject, { group: e.target.value })}><option value="">Choisir un groupe</option><option>Groupe A</option><option>Groupe B</option><option>Groupe C</option></select></label><fieldset><legend>Tarification</legend><label className={details.priceType === 'standard' ? 'active' : ''}><input type="radio" name={`${subject}-price`} checked={details.priceType === 'standard'} onChange={() => setSubjectDetails(subject, { priceType: 'standard' })} /><span><b>Prix standard</b><small>{price(subject)} DH/mois</small></span></label><label className={details.priceType === 'manual' ? 'active' : ''}><input type="radio" name={`${subject}-price`} checked={details.priceType === 'manual'} onChange={() => setSubjectDetails(subject, { priceType: 'manual' })} /><span><b>Prix manuel</b><input type="number" min="0" placeholder="Montant DH" disabled={details.priceType !== 'manual'} value={details.manualPrice} onChange={e => setSubjectDetails(subject, { manualPrice: e.target.value })} /></span></label></fieldset></div>}</article> })}</div><footer><button onClick={() => setEditing(null)}>Annuler</button><button className="validate-button" onClick={saveEdit}>Enregistrer</button></footer></section></div>}</div>
}
