/* eslint-disable no-irregular-whitespace */
import { useState } from 'react'
import Header from '../shared/Header'
import './Settings.css'


const subjects = ['Mathématiques', 'Français', 'Arabe', 'Physique', 'SVT', 'Anglais', 'Physique-Chimie', 'Philosophie']
const initialLevels = [['7ème (1AC)', 300], ['8ème (2AC)', 300], ['9ème (3AC)', 300], ['Tronc commun', 450], ['1ère Bac', 450], ['2ème Bac', 450]]
const textDefault = 'Bonjour, ceci est un rappel du Centre Atlas concernant les frais de scolarité de {nom_eleve} pour le mois de {mois}.\n\nMontant dû : {montant_du}.\n\nMerci de régulariser dès que possible.\n— Centre Atlas'

function Dialog({ title, type, close, save }) { const [name, setName] = useState(''); return <div className="settings-dialog-bg" onMouseDown={close}><section className="settings-dialog" onMouseDown={e => e.stopPropagation()}><button className="settings-close" onClick={close}>×</button><h2>{title}</h2><label>{type === 'level' ? 'Nom du niveau' : 'Nom de la matière'}<input autoFocus value={name} onChange={e => setName(e.target.value)} placeholder={type === 'level' ? 'ex : 4ème année collège' : 'ex : Philosophie'} /></label>{type === 'subject' && <label>Prix (DH / mois)<input defaultValue="300" /></label>}<footer><button className="settings-outline" onClick={close}>Annuler</button><button className="settings-save" onClick={() => name.trim() && save(name)}>Enregistrer</button></footer></section></div> }

export default function Settings() { const [tab, setTab] = useState('general'); const [levels, setLevels] = useState(initialLevels); const [extras, setExtras] = useState([]); const [modal, setModal] = useState(''); const [message, setMessage] = useState(textDefault); const allSubjects = [...subjects, ...extras]; const preview = message.replace('{nom_eleve}', 'Yasmine Alaoui').replace('{mois}', 'Février 2026').replace('{montant_du}', '1 200 DH'); const add = n => { if (modal === 'level') setLevels(x => [...x, [n, 300]]); else setExtras(x => [...x, n]); setModal('') }
 return <div className="settings-page"><Header /><main className="settings-content"><h1>Paramètres</h1><p>Configuration générale de la plateforme.</p><nav className="settings-tabs">{[['general', '▦ Général'], ['pricing', '⛓ Grille tarifaire'], ['whatsapp', '□ Template WhatsApp']].map(([id, label]) => <button className={tab === id ? 'active' : ''} onClick={() => setTab(id)} key={id}>{label}</button>)}</nav>{tab === 'general' && <section className="settings-card settings-general"><div><label>Nom du centre<input defaultValue="Centre Atlas" /></label><label>Adresse principale<input defaultValue="12 Bd Zerktouni, Casablanca" /></label><div className="settings-two"><label>Téléphone<input defaultValue="0522334455" /></label><label>Email<input defaultValue="contact@centre-atlas.ma" /></label></div></div><label className="settings-logo">⇧<span>Importer un logo</span><input type="file" hidden /></label><button className="settings-save">▣　Enregistrer</button></section>}{tab === 'pricing' && <section className="settings-card settings-pricing"><header><div><strong>Grille tarifaire (DH / mois)</strong><p>Prix standard appliqué automatiquement par niveau et par matière.</p></div><button className="settings-outline" onClick={() => setModal('level')}>＋　Ajouter un niveau</button></header><div className="settings-table"><table><thead><tr><th>Niveau</th>{allSubjects.map(s => <th key={s}>{s}</th>)}<th>Actions</th></tr></thead><tbody>{levels.map(([l, v]) => <tr key={l}><th>{l}</th>{allSubjects.map(s => <td key={s}><input defaultValue={v} /> ♲</td>)}<td><button onClick={() => setModal('subject')}>＋　Matière</button></td></tr>)}</tbody></table></div><footer>Total moyen : 375 DH <button className="settings-save">▣　Enregistrer</button></footer></section>}{tab === 'whatsapp' && <section className="settings-card settings-whatsapp"><label>Message de rappel WhatsApp<small>Variables disponibles : <b>{'{nom_eleve}'}</b>, <b>{'{mois}'}</b>, <b>{'{montant_du}'}</b></small><textarea value={message} onChange={e => setMessage(e.target.value)} /></label><div className="settings-preview"><small>APERÇU</small><p>{preview}</p></div><button className="settings-save">▣　Enregistrer</button></section>}</main>{modal && <Dialog type={modal} title={modal === 'level' ? 'Ajouter un niveau' : `Ajouter une matière — ${levels[0][0]}`} close={() => setModal('')} save={add} />}</div> }
